project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: workflow.qmd
        text: About the Workflow

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true